# title: Ana M. Tárano's Portfolio Website
description: *[Linkedin](https://www.linkedin.com/in/anatarano/)
* [GitHub](https://github.com/anatarano/)
* [Email](anatarano@gmail.com)

logo: 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
