# title: Ana M. Tárano's Portfolio Website
description: 

linkedin_username: anatarano
# * [GitHub](https://github.com/anatarano/)
# * [Email](anatarano@gmail.com)
author :
  name : Ana M. Tarano
  email : anatarano@gmail.com
  github : anatarano

logo: 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
